services:
  hc-db-dynamodb:
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    image: "amazon/dynamodb-local:latest"
    ports:
      - "8000:8000"
    restart: always
    user: root
    volumes:
      - dynamodb_data:/home/dynamodblocal/data
    working_dir: /home/dynamodblocal
    networks:
      - home_network
  hc-ap:
    image: hc:1.0
    build:
      context: .
      dockerfile: ./docker/web-ap/Dockerfile
    restart: always
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: http://hc-db-dynamodb:8000
    networks:
      - home_network
networks:
  home_network:
    external: true
volumes:
  dynamodb_data:
    name: hc-dynamodb-data
