AWSTemplateFormatVersion: "2010-09-09"
Description: DynamoDB Table for Messages

Resources:
  MessageTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: message
      AttributeDefinitions:
        - AttributeName: createdAt
          AttributeType: S
        - AttributeName: channelId
          AttributeType: S
      KeySchema:
        - AttributeName: channelId
          KeyType: HASH
        - AttributeName: createdAt
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
