spring:
  config:
    import: optional:configtree:/run/secrets/
  cloud:
    aws:
      dynamodb:
        enabled: true
        region: eu-west-1
        endpoint: ${DYNAMODB_URL:http://localhost:8000}
      credentials:
        secret-key: DUMMYEXAMPLEKEY
        access-key: DUMMYIDEXAMPLE
  datasource:
    url: ${HMS_DATASOURCE_URL:jdbc:mariadb://localhost:13306/hms}
    driver-class-name: org.mariadb.jdbc.Driver
    username: hms
    password: ${mysql_user_password}
  ai:
    ollama:
      base-url: ${SPRING_AI_MODEL_HOST:http://192.168.10.11:11434}
      chat:
        options:
          model: qwen3:0.6b
          temperature: 0.7
      embedding:
        options:
          model: nomic-embed-text
api:
  hms:
    base-url: ${SPRING_AI_HMS_HOST:http://localhost:8080/hms}
    username: ${hms_api_username:admin}
    password: ${hms_api_password:password}