spring:
  cloud:
    aws:
      dynamodb:
        enabled: true
        region: eu-west-1
        endpoint: ${SPRING_DATASOURCE_URL:http://localhost:8000}
      credentials:
        secret-key: DUMMYEXAMPLEKEY
        access-key: DUMMYIDEXAMPLE

ai:
  sse:
    host: ${SPRING_AI_SSE_HOST:http://localhost} 
  model:
    host: ${SPRING_AI_MODEL_HOST:http://localhost:12434}
