spring:
  application:
    name: hc
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  cloud:
    aws:
      dynamodb:
        enabled: true
        region: eu-west-1
        endpoint: http://localhost:18000
      credentials:
        secret-key: DUMMYEXAMPLEKEY
        access-key: DUMMYIDEXAMPLE
springdoc:
  swagger-ui:
    path: /swagger-ui.html
